name: Build and run integration tests

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        default: 'sse-c'
        required: true

env:
  S3_TEST_REGION :  ${{ vars.S3_TEST_REGION }}
  S3_TEST_BUCKET : ${{ vars.S3_TEST_BUCKET }}
  S3_TEST_PREFIX : ${{ vars.S3_TEST_PREFIX }}
  ROLE_TO_ASSUME: ${{ secrets.S3_TEST_ASSUME_ROLE_ARN }}
  CUSTOMER_KEY: ${{ secrets.CUSTOMER_KEY }}

jobs:
  build:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: integration-tests
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.event.pull_request.head.sha }}
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.S3_TEST_REGION }}

    - name: Build with Gradle Wrapper
      run: ./gradlew :input-stream:integrationTest --tests "software.amazon.s3.analyticsaccelerator.access.SSECEncryptionTest"
